An error occurred while executing the following cell:
------------------
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import patsy
import scipy
import statsmodels.api as sm
import statsmodels.formula.api as smf
from tests_as_linear import plots, utils

np.random.seed(1618)
------------------

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_4162/3914771595.py in <module>
      2 import numpy as np
      3 import pandas as pd
----> 4 import patsy
      5 import scipy
      6 import statsmodels.api as sm

ModuleNotFoundError: No module named 'patsy'
ModuleNotFoundError: No module named 'patsy'
