An error occurred while executing the following cell:
------------------
sngp_pred_train = train_and_test_sngp(np.array(X_train), np.array(X_train))
------------------

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_4092/3946251102.py in <module>
----> 1 sngp_pred_train = train_and_test_sngp(np.array(X_train), np.array(X_train))

/tmp/ipykernel_4092/3178864071.py in train_and_test_sngp(X_train, X_test)
      3 
      4     sngp_model.compile(**train_config)
----> 5     sngp_model.fit(X_train, np.array(y_train), verbose=0, **fit_config)
      6 
      7     sngp_logits, sngp_covmat = sngp_model(X_test, return_covmat=True)

/tmp/ipykernel_4092/3636043544.py in fit(self, *args, **kwargs)
      5         kwargs["callbacks"].append(ResetCovarianceCallback())
      6 
----> 7         return super().fit(*args, **kwargs)

~/miniconda3/envs/py37/lib/python3.7/site-packages/keras/utils/traceback_utils.py in error_handler(*args, **kwargs)
     68             # To get the full stack trace, call:
     69             # `tf.debugging.disable_traceback_filtering()`
---> 70             raise e.with_traceback(filtered_tb) from None
     71         finally:
     72             del filtered_tb

~/miniconda3/envs/py37/lib/python3.7/site-packages/keras/optimizers/optimizer_experimental/optimizer.py in _update_step(self, gradient, variable)
    215         Returns:
    216           A list of (gradient, variable) pairs. Variable is always present, but
--> 217           gradient can be `None`.
    218         """
    219         if not callable(loss) and tape is None:

KeyError: 'The optimizer cannot recognize variable deep_res_net_sngp_with_cov_reset_1/spectral_normalization_6/kernel:0. This usually means you are trying to call the optimizer to update different parts of the model separately. Please call `optimizer.build(variables)` with the full list of trainable variables before the training loop or use legacy optimizer `tf.keras.optimizers.legacy.{self.__class__.__name__}.'
KeyError: 'The optimizer cannot recognize variable deep_res_net_sngp_with_cov_reset_1/spectral_normalization_6/kernel:0. This usually means you are trying to call the optimizer to update different parts of the model separately. Please call `optimizer.build(variables)` with the full list of trainable variables before the training loop or use legacy optimizer `tf.keras.optimizers.legacy.{self.__class__.__name__}.'
