An error occurred while executing the following cell:
------------------
x, y, lgssm_posterior = kf_spiral()

dict_figures = plot_kf_spiral(x, y, lgssm_posterior)

for k, v in dict_figures.items():
    fname = k + ".pdf"
    print(fname)
    fig = v
    # fig.savefig(fname)
------------------

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_3454/1480924929.py in <module>
----> 1 x, y, lgssm_posterior = kf_spiral()
      2 
      3 dict_figures = plot_kf_spiral(x, y, lgssm_posterior)
      4 
      5 for k, v in dict_figures.items():

/tmp/ipykernel_3454/178339242.py in kf_spiral()
      6 
      7     lgssm = LinearGaussianSSM(state_dim, emission_dim)
----> 8     params, _ = lgssm.random_initialization(jr.PRNGKey(0))
      9     params["initial"]["mean"] = jnp.array([8.0, 10.0, 1.0, 0.0])
     10     params["initial"]["cov"] = jnp.eye(state_dim) * 0.1

AttributeError: 'LinearGaussianSSM' object has no attribute 'random_initialization'
AttributeError: 'LinearGaussianSSM' object has no attribute 'random_initialization'
