An error occurred while executing the following cell:
------------------
rng = jax.random.PRNGKey(1)
init_model_params = model_transform.init(rng, dist1.rvs(BATCH_SIZE))
------------------

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_3984/2939590280.py in <module>
      1 rng = jax.random.PRNGKey(1)
----> 2 init_model_params = model_transform.init(rng, dist1.rvs(BATCH_SIZE))

~/miniconda3/envs/py37/lib/python3.7/site-packages/haiku/_src/transform.py in init_fn(*args, **kwargs)
    112 
    113   def init_fn(*args, **kwargs):
--> 114     params, state = f.init(*args, **kwargs)
    115     if state:
    116       raise ValueError("If your transformed function uses `hk.{get,set}_state` "

~/miniconda3/envs/py37/lib/python3.7/site-packages/haiku/_src/transform.py in init_fn(rng, *args, **kwargs)
    336     with base.new_context(rng=rng) as ctx:
    337       try:
--> 338         f(*args, **kwargs)
    339       except jax.errors.UnexpectedTracerError as e:
    340         raise jax.errors.UnexpectedTracerError(unexpected_tracer_hint) from e

/tmp/ipykernel_3984/1178261919.py in <lambda>(*args, **kwargs)
      2     hk.transform(
      3         lambda *args, **kwargs: hk.Sequential(
----> 4             [hk.Linear(10), jax.nn.relu, hk.Linear(10), jax.nn.tanh, hk.Linear(40), hk.Linear(1)]
      5         )(*args, **kwargs)
      6     )

~/miniconda3/envs/py37/lib/python3.7/site-packages/haiku/_src/module.py in __call__(cls, *args, **kwargs)
    121     # Now attempt to initialize the object.
    122     init = wrap_method("__init__", cls.__init__)
--> 123     init(module, *args, **kwargs)
    124 
    125     if (config.get_config().module_auto_repr and

~/miniconda3/envs/py37/lib/python3.7/site-packages/haiku/_src/module.py in wrapped(self, *args, **kwargs)
    419       f = functools.partial(unbound_method, self)
    420       f = functools.partial(run_interceptors, f, method_name, self)
--> 421       if jax.config.jax_experimental_name_stack and module_name:
    422         local_module_name = module_name.split("/")[-1]
    423         f = jax.named_call(f, name=local_module_name)

AttributeError: 'Config' object has no attribute 'jax_experimental_name_stack'
AttributeError: 'Config' object has no attribute 'jax_experimental_name_stack'
